import type { LegoPortContractFixture } from "@helix/contracts"

const promptProductSupportAliasImplementationKinds = Object.fromEntries(
  [
    "opencode.resource.discovery",
    "pi.resource.discovery",
    "nanobot.resource.discovery",
    "hermes.resource.discovery",
    "opencode.prompt.resource-loader",
    "pi.prompt.resource-loader",
    "nanobot.prompt.resource-loader",
    "hermes.prompt.resource-loader",
    "opencode.prompt.tool-renderer",
    "pi.prompt.tool-renderer",
    "nanobot.prompt.tool-renderer",
    "hermes.prompt.tool-renderer",
    "opencode.prompt.model-adapter",
    "pi.prompt.model-adapter",
    "nanobot.prompt.model-adapter",
    "hermes.prompt.model-adapter",
    "opencode.prompt.compaction-adapter",
    "pi.prompt.compaction-adapter",
    "nanobot.prompt.compaction-adapter",
    "hermes.prompt.compaction-adapter",
  ].map((id) => [id, "metadata-only"] as const),
)

const promptSystemBuilderPersonalityImplementationKinds = {
  "opencode.prompt.mode-builder": "factory",
} as const

const promptProductSupportImplementationKinds = {
  ...promptProductSupportAliasImplementationKinds,
  "opencode.resource.discovery.instruction": "factory",
  "opencode.prompt.resource-loader.instruction": "factory",
  "opencode.prompt.tool-renderer.provider-tools": "factory",
  "opencode.prompt.model-capability-adapter.provider-prompt": "factory",
  "opencode.prompt.compaction-adapter.build-prompt": "factory",
  "pi.resource.discovery.project-context": "factory",
  "pi.prompt.resource-loader.project-context": "factory",
  "pi.prompt.tool-renderer.runtime-tools": "factory",
  "pi.prompt.model-capability-adapter.runtime-model": "factory",
  "pi.prompt.compaction-adapter.summary-mode": "factory",
} as const

export const promptPortContractFixtures: LegoPortContractFixture[] = [
  {
    id: "resource.discovery",
    input: "workspace, config, product conventions, include/exclude filters, and resource type hints",
    output: "discovered prompt/rule/skill/theme/asset resource descriptors with source metadata",
    lifecycle: ["workspace", "session"],
    resources: [{ id: "filesystem", mode: "read", scope: "workspace" }],
    conformance: "prompt:resource-discovery",
    implementations: ["resource.discovery.filesystem", "resource.discovery.memory"],
    personalityAtoms: ["opencode.resource.discovery", "opencode.resource.discovery.instruction", "pi.resource.discovery", "pi.resource.discovery.project-context", "nanobot.resource.discovery", "hermes.resource.discovery"],
    personalityAtomImplementationKinds: promptProductSupportImplementationKinds,
  },
  {
    id: "prompt.resource-loader",
    input: "resource descriptors, loader registry, encoding policy, and redaction policy",
    output: "loaded text/markdown/structured prompt resources with stable provenance metadata",
    lifecycle: ["workspace", "session", "turn"],
    resources: [{ id: "filesystem", mode: "read", scope: "workspace" }],
    conformance: "prompt:resource-loader",
    implementations: ["prompt.resource-loader.text", "prompt.resource-loader.markdown"],
    personalityAtoms: ["opencode.prompt.resource-loader", "opencode.prompt.resource-loader.instruction", "pi.prompt.resource-loader", "pi.prompt.resource-loader.project-context", "nanobot.prompt.resource-loader", "hermes.prompt.resource-loader"],
    personalityAtomImplementationKinds: promptProductSupportImplementationKinds,
  },
  {
    id: "prompt.system-builder",
    input: "base prompt resources, mode/persona settings, session context, tool summaries, and product rules",
    output: "normalized system/developer prompt messages ready for provider request assembly",
    lifecycle: ["turn"],
    resources: [],
    conformance: "prompt:system-builder",
    implementations: ["prompt.system-builder.common"],
    personalityAtoms: ["opencode.prompt.mode-builder", "pi.prompt.coding-agent-builder", "nanobot.prompt.agent-builder", "hermes.prompt.agent-builder"],
    personalityAtomImplementationKinds: promptSystemBuilderPersonalityImplementationKinds,
  },
  {
    id: "prompt.tool-renderer",
    input: "tool definitions, schema adapter output, provider capability metadata, and product render preferences",
    output: "provider/tool prompt description payload plus render diagnostics",
    lifecycle: ["turn"],
    resources: [],
    conformance: "prompt:tool-renderer",
    implementations: ["prompt.tool-renderer.common"],
    personalityAtoms: ["opencode.prompt.tool-renderer", "opencode.prompt.tool-renderer.provider-tools", "pi.prompt.tool-renderer", "pi.prompt.tool-renderer.runtime-tools", "nanobot.prompt.tool-renderer", "hermes.prompt.tool-renderer"],
    personalityAtomImplementationKinds: promptProductSupportImplementationKinds,
  },
  {
    id: "prompt.model-capability-adapter",
    input: "model metadata, provider capability flags, prompt sections, tools, and reasoning settings",
    output: "prompt/tool/request adjustments for selected model capabilities and quirks",
    lifecycle: ["turn"],
    resources: [],
    conformance: "prompt:model-capability-adapter",
    implementations: ["prompt.model-capability-adapter.common"],
    personalityAtoms: ["opencode.prompt.model-adapter", "opencode.prompt.model-capability-adapter.provider-prompt", "pi.prompt.model-adapter", "pi.prompt.model-capability-adapter.runtime-model", "nanobot.prompt.model-adapter", "hermes.prompt.model-adapter"],
    personalityAtomImplementationKinds: promptProductSupportImplementationKinds,
  },
  {
    id: "prompt.compaction-adapter",
    input: "compaction summary, retained transcript slice, model budget, product prompt conventions, and continuation policy",
    output: "provider-ready compaction prompt or synthetic continuation instruction with traceable provenance",
    lifecycle: ["session", "turn"],
    resources: [],
    conformance: "prompt:compaction-adapter",
    implementations: ["prompt.compaction-adapter.common"],
    personalityAtoms: ["opencode.prompt.compaction-adapter", "opencode.prompt.compaction-adapter.build-prompt", "pi.prompt.compaction-adapter", "pi.prompt.compaction-adapter.summary-mode", "nanobot.prompt.compaction-adapter", "hermes.prompt.compaction-adapter"],
    personalityAtomImplementationKinds: promptProductSupportImplementationKinds,
  },
]
