import type { LegoPortContractFixture } from "@helix/contracts"

export const runtimePortContractFixtures: LegoPortContractFixture[] = [
  {
    id: "runtime.module-catalog",
    input: "module manifests, atom manifests, pack expansions, product shell manifests, and registration source metadata",
    output: "queryable module catalog with duplicate-id diagnostics and public manifest inventory",
    lifecycle: ["process"],
    resources: [],
    conformance: "runtime:module-catalog",
    implementations: ["runtime.module-catalog.memory"],
    personalityAtoms: ["opencode.runtime.module-catalog", "opencode.runtime.module-aliases", "pi.runtime.module-catalog", "pi.runtime.module-aliases", "nanobot.runtime.module-aliases", "hermes.runtime.module-aliases"],
  },
  {
    id: "runtime.capability-resolver",
    input: "selected module manifests, required/optional capability refs, explicit bindings, and multiplicity rules",
    output: "validated dependency order with missing, incompatible, cyclic, or ambiguous capability diagnostics",
    lifecycle: ["process"],
    resources: [],
    conformance: "runtime:capability-resolver",
    implementations: ["runtime.capability-resolver.default"],
    personalityAtoms: ["opencode.runtime.capability-resolver", "opencode.runtime.capability-aliases", "pi.runtime.capability-resolver", "pi.runtime.capability-aliases", "nanobot.runtime.capability-aliases", "hermes.runtime.capability-aliases"],
  },
  {
    id: "runtime.binding-planner",
    input: "recipe modules, atom refs, pack expansions, product shells, overrides, and capability candidates",
    output: "deterministic port-to-atom binding plan with explicit/implicit/candidate evidence",
    lifecycle: ["process"],
    resources: [],
    conformance: "runtime:binding-planner",
    implementations: ["runtime.binding-planner.lockfile"],
    personalityAtoms: ["opencode.runtime.binding-planner", "opencode.runtime.binding-defaults", "pi.runtime.binding-planner", "pi.runtime.binding-defaults", "nanobot.runtime.binding-defaults", "hermes.runtime.binding-defaults"],
  },
  {
    id: "runtime.lifecycle-runner",
    input: "resolved module order, lifecycle scope, module config, service tokens, resource grants, and dispose reason",
    output: "initialized service context, started module instances, and scoped disposal trace",
    lifecycle: ["process", "workspace", "session", "turn", "tool-call"],
    resources: [],
    conformance: "runtime:lifecycle-runner",
    implementations: ["runtime.lifecycle-runner.scoped"],
    personalityAtoms: ["opencode.runtime.lifecycle-runner", "opencode.runtime.lifecycle-defaults", "pi.runtime.lifecycle-runner", "pi.runtime.lifecycle-defaults", "nanobot.runtime.lifecycle-defaults", "hermes.runtime.lifecycle-defaults"],
  },
  {
    id: "runtime.assembly-graph",
    input: "resolved modules, capability bindings, pack expansions, recipes, resources, strategies, and policies",
    output: "graph and lockfile views for audit, docs, CLI inspect/diff/graph/validate, and replay diagnostics",
    lifecycle: ["process"],
    resources: [{ id: "filesystem", mode: "write", scope: "workspace" }],
    conformance: "runtime:assembly-graph",
    implementations: ["runtime.assembly-graph.lockfile"],
    personalityAtoms: ["opencode.runtime.assembly-graph", "opencode.runtime.graph-labels", "pi.runtime.assembly-graph", "pi.runtime.graph-labels", "nanobot.runtime.graph-labels", "hermes.runtime.graph-labels"],
  },
  {
    id: "runtime.acceptance-controller",
    input: "task policy evidence, workspace diff evidence, tool results, provider stop reason, and product mode",
    output: "accept, continue, summarize, fail, or inconclusive decision with reason code",
    lifecycle: ["turn"],
    resources: [{ id: "filesystem", mode: "read", scope: "workspace" }],
    conformance: "runtime:acceptance-controller",
    implementations: ["common.runtime.acceptance-controller.default"],
    personalityAtoms: [
      "opencode.runtime.acceptance-controller.native-like",
      "pi.runtime.acceptance-controller.native-like",
      "nanobot.runtime.acceptance-controller.native-like",
      "hermes.runtime.acceptance-controller.native-like",
    ],
  },
  {
    id: "runtime.acceptance-evidence",
    input: "task policy, workspace before/after snapshot, visible assistant text, tool calls/results, required commands, forbidden files, and provider stop evidence",
    output: "product-neutral acceptance evidence with normalized checks, workspace diff signature, tool calls, and pass/fail summary",
    lifecycle: ["turn"],
    resources: [{ id: "filesystem", mode: "read", scope: "workspace" }],
    conformance: "runtime:acceptance-evidence",
    implementations: ["common.runtime.acceptance-evidence.default"],
    personalityAtoms: [
      "opencode.runtime.acceptance-evidence.native-like",
      "pi.runtime.acceptance-evidence.native-like",
      "nanobot.runtime.acceptance-evidence.native-like",
      "hermes.runtime.acceptance-evidence.native-like",
    ],
  },
]
