import type { LegoPortContractFixture } from "@helix/contracts"

export const turnPortContractFixtures: LegoPortContractFixture[] = [
  {
    id: "turn.input-normalizer",
    input: "raw product/user input, shell metadata, session context, and abort signal",
    output: "normalized turn input with text, attachments, options, and source metadata",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:input-normalizer",
    implementations: ["turn.input-normalizer.text"],
    personalityAtoms: ["opencode.turn.input-normalizer", "pi.turn.input-normalizer", "nanobot.turn.input-normalizer", "hermes.turn.input-normalizer"],
  },
  {
    id: "turn.context-builder",
    input: "session transcript, context selector, token budget, compaction records, and model metadata",
    output: "provider-ready context messages, token estimate, overflow decision, and compaction request",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:context-builder",
    implementations: ["turn.context-builder.transcript"],
    personalityAtoms: ["opencode.turn.context-builder", "pi.turn.context-builder", "nanobot.turn.context-builder", "hermes.turn.context-builder"],
  },
  {
    id: "turn.prompt-assembler",
    input: "system prompt resources, tool definitions, provider/model capabilities, rules, and mode settings",
    output: "assembled system/developer/tool prompt payload for provider request shaping",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:prompt-assembler",
    implementations: ["turn.prompt-assembler.common"],
    personalityAtoms: ["opencode.turn.prompt-assembler", "pi.turn.prompt-assembler", "nanobot.turn.prompt-assembler", "hermes.turn.prompt-assembler"],
  },
  {
    id: "turn.provider-request-builder",
    input: "normalized input, assembled prompt, selected model/provider, context messages, tools, and options",
    output: "common ProviderRequest plus provider-personality request-shape hints",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:provider-request-builder",
    implementations: ["turn.provider-request-builder.common"],
    personalityAtoms: ["opencode.turn.provider-request-builder", "pi.turn.provider-request-builder", "nanobot.turn.provider-request-builder", "hermes.turn.provider-request-builder"],
  },
  {
    id: "turn.provider-stream-runner",
    input: "ProviderRequest, provider stream port, retry metadata, lifecycle hooks, and abort signal",
    output: "ordered provider stream events and transport diagnostics",
    lifecycle: ["turn"],
    resources: [{ id: "network", mode: "execute", scope: "external" }],
    conformance: "agent-loop:provider-stream-runner",
    implementations: ["turn.provider-stream-runner.common"],
    personalityAtoms: ["opencode.turn.provider-stream-runner", "pi.turn.provider-stream-runner", "nanobot.turn.provider-stream-runner", "hermes.turn.provider-stream-runner"],
  },
  {
    id: "turn.stream-reducer",
    input: "ProviderStreamEvent sequence for text, reasoning, parts, tool calls, usage, finish, and errors",
    output: "assistant message parts, pending tool calls, finish state, usage, and reducer trace",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:stream-reducer",
    implementations: ["turn.stream-reducer.common"],
    personalityAtoms: ["opencode.turn.stream-reducer", "pi.turn.stream-reducer", "nanobot.turn.stream-reducer", "hermes.turn.stream-reducer"],
  },
  {
    id: "turn.tool-call-planner",
    input: "pending tool calls, tool definitions, execution modes, permission policy, and product ordering strategy",
    output: "deterministic tool execution batches with sequential/parallel ordering evidence",
    lifecycle: ["turn", "tool-call"],
    resources: [],
    conformance: "agent-loop:tool-call-planner",
    implementations: ["turn.tool-call-planner.parallel-batch", "turn.tool-call-planner.sequential"],
    personalityAtoms: ["opencode.turn.tool-call-planner", "pi.turn.tool-call-planner", "nanobot.turn.tool-call-planner", "hermes.turn.tool-call-planner"],
  },
  {
    id: "turn.tool-executor",
    input: "planned tool calls, tool executor port, permission decisions, lifecycle hooks, and abort signal",
    output: "ordered tool results, execution traces, and transcript-safe result parts",
    lifecycle: ["turn", "tool-call"],
    resources: [
      { id: "filesystem", mode: "write", scope: "workspace" },
      { id: "shell", mode: "execute", scope: "process" },
    ],
    conformance: "agent-loop:tool-executor",
    implementations: ["turn.tool-executor.common"],
    personalityAtoms: ["opencode.turn.tool-executor", "pi.turn.tool-executor", "nanobot.turn.tool-executor", "hermes.turn.tool-executor"],
  },
  {
    id: "turn.result-recorder",
    input: "assistant message, tool results, usage metadata, trace records, and session writer/store ports",
    output: "persisted assistant/tool transcript records and product event projections",
    lifecycle: ["turn", "session"],
    resources: [{ id: "filesystem", mode: "write", scope: "workspace" }],
    conformance: "agent-loop:result-recorder",
    implementations: ["turn.result-recorder.common"],
    personalityAtoms: ["opencode.turn.result-recorder", "pi.turn.result-recorder", "nanobot.turn.result-recorder", "hermes.turn.result-recorder"],
  },
  {
    id: "turn.retry-policy",
    input: "provider/tool error, attempt count, model/provider metadata, and configured retry strategy",
    output: "retry, backoff, fail, or provider_error message decision",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:retry-policy",
    implementations: ["turn.retry-policy.none", "turn.retry-policy.fixed", "turn.retry-policy.exponential"],
    personalityAtoms: ["opencode.turn.retry-policy", "pi.turn.retry-policy", "nanobot.turn.retry-policy", "hermes.turn.retry-policy"],
  },
  {
    id: "turn.continuation-policy",
    input: "finish reason, length state, compaction state, previous assistant message, and provider options",
    output: "stop, continue, or synthetic message injection decision",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:continuation-policy",
    implementations: ["turn.continuation-policy.none", "turn.continuation-policy.synthetic-continue"],
    personalityAtoms: ["opencode.turn.continuation-policy", "pi.turn.continuation-policy", "nanobot.turn.continuation-policy", "hermes.turn.continuation-policy"],
  },
  {
    id: "turn.compaction-policy",
    input: "token estimate, transcript, compaction records, model budget, and product compaction settings",
    output: "no-op, compact-now, or compact-and-autocontinue decision plus summary input",
    lifecycle: ["turn", "session"],
    resources: [{ id: "filesystem", mode: "write", scope: "workspace" }],
    conformance: "agent-loop:compaction-policy",
    implementations: ["turn.compaction-policy.none", "turn.compaction-policy.token-threshold", "turn.compaction-policy.manual"],
    personalityAtoms: ["opencode.turn.compaction-policy", "pi.turn.compaction-policy", "nanobot.turn.compaction-policy", "hermes.turn.compaction-policy"],
  },
  {
    id: "turn.stop-condition",
    input: "step count, pending tool calls, finish reason, max steps, cancellation state, and continuation decision",
    output: "stop or continue decision with reason and trace metadata",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:stop-condition",
    implementations: ["turn.stop-condition.no-tool-calls", "turn.stop-condition.max-steps"],
    personalityAtoms: ["opencode.turn.stop-condition", "pi.turn.stop-condition", "nanobot.turn.stop-condition", "hermes.turn.stop-condition"],
  },
  {
    id: "agent-loop.request-boundary",
    input: "provider finish reason, tool-call count, acceptance state, synthetic continue count, and product turn profile",
    output: "continue, stop, or synthetic-continue decision with product-native request boundary evidence",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:request-boundary",
    implementations: ["common.agent-loop.request-boundary.default"],
    personalityAtoms: [
      "opencode.agent-loop.request-boundary.native-like",
      "pi.agent-loop.request-boundary.native-like",
      "nanobot.agent-loop.request-boundary.native-like",
      "hermes.agent-loop.request-boundary.native-like",
    ],
  },
  {
    id: "agent-loop.final-summary",
    input: "tool result state, task acceptance state, provider stop reason, visible text state, and product profile",
    output: "none, concise-summary, native-final-message, or force-provider-round decision with trace evidence",
    lifecycle: ["turn"],
    resources: [],
    conformance: "agent-loop:final-summary",
    implementations: ["common.agent-loop.final-summary.default"],
    personalityAtoms: [
      "opencode.agent-loop.final-summary.native-like",
      "pi.agent-loop.final-summary.native-like",
      "nanobot.agent-loop.final-summary.native-like",
      "hermes.agent-loop.final-summary.native-like",
    ],
  },
]
